name: publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: latest
          gleam-version: latest

      - name: Download Gleam dependencies
        run: gleam deps download

      - name: Publish to Hex
        run: gleam publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
