name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime: [node, bun, deno]
    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          otp-version: latest
          gleam-version: latest
          rebar3-version: "3"
          # elixir-version: "1"
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - uses: oven-sh/setup-bun@v2
        if: matrix.runtime == 'bun'
      - uses: denoland/setup-deno@v2
        if: matrix.runtime == 'deno'
        with:
          deno-version: "v2.x"
      - run: npm ci
      - run: gleam deps download
      - run: gleam test --runtime ${{ matrix.runtime }}
      - run: gleam format --check src test
        if: matrix.runtime == 'node'
